---

version: "3.3"

services:

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: "jimmy/nginx"
    container_name: nginx
#    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: "jimmy/php-fpm"
    container_name: app
    restart: unless-stopped
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: "jimmy/node"
    container_name: node
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
    networks:
      - appnet

  database:
    image: mysql:5.7.22
    container_name: database
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - appnet

  composer:
    image: composer:1.6
    container_name: composer
    user: "1000:1000"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
    working_dir: ${DOCUMENT_ROOT}
    entrypoint: composer install

networks:
  appnet:
    driver: "bridge"

volumes:
  nginx_db_data:
